fallback_zxing: true
steps:
- name: direct
- name: upsample
  scale: 1.5
- method: adaptive
  name: threshold
- name: deskew
- angles:
  - -45
  - -30
  - -10
  - 0
  - 10
  - 30
  - 45
  name: rot_try
time_budget_ms: 400
