time_budget_ms: 180
steps:
  - name: direct
#  - name: zxing_quick
#  - name: upsample
#    scale: 1.5
  - name: threshold
    method: adaptive
  - name: deskew
  - name: rot_try
    angles: [-45,-30,-10, 0, 10, 30, 45]
fallback_zxing: true


